version: "3.8"
services: 
    redis:
        container_name: redis
        image: redis:latest
        ports:
            - 6379:6379
        volumes:
            - ./redis:/redis
        command: [ "redis-server"]
   
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3.13.1-management
        ports:
            - 5672:5672
            - 15672:15672        
        environment:
          RABBITMQ_DEFAULT_USER: "user"
          RABBITMQ_DEFAULT_PASS: "password"
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
   
    mongodb:
        image: mongo:latest
        container_name: mongodb_example
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: secret
        ports:
            - 27017:27017
        volumes:
            - mongo-data:/data/db
    mysql-db:
        image: mysql
        container_name: mysql_example
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=example1
        ports:
            - 3306:3306
        volumes:
            - mysql-data:/var/lib/mysql

volumes: 
    redis-data:
    rabbitmq_data:
    rabbitmq_log:
    mongo-data:
    mysql-data:

