version: "3.7"
services: 
    redis:
        container_name: redis
        image: redis:7.2.4
        ports:
            - 6379:6379
        volumes:
            - ./redis:/redis
        command: [ "redis-server"]
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3.13.1-alpine
        ports:
            - 5672:5672
            - 15672:15672        
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
