import { CustomData } from "./data-structure/CustomData";

export const persons: CustomData[] = [
  {
    nombre: "Adrian",
    apellido: "Perez",
    cedula: "12345678",
    telefono: "095000111",
    departamento: "MONTEVIDEO",
    necesita_asistencia_movilidad: false,
  },
  {
    nombre: "Juan",
    apellido: "Garcia",
    cedula: "1234567",
    telefono: "095030111",
    departamento: "MONTEVIDEO",
    necesita_asistencia_movilidad: false,
  },
  {
    nombre: "Seba",
    apellido: "Martinez",
    cedula: "02345678",
    telefono: "095000111",
    departamento: "MONTEVIDEO",
    necesita_asistencia_movilidad: false,
  },
  {
    nombre: "Martin",
    apellido: "Lucrecio",
    cedula: "0345678",
    telefono: "095000111",
    departamento: "MONTEVIDEO",
    necesita_asistencia_movilidad: false,
  },
  {
    nombre: "Matias",
    apellido: "Ramirez",
    cedula: "123456",
    telefono: "095000111",
    departamento: "MONTEVIDEO",
    necesita_asistencia_movilidad: false,
  },
  {
    nombre: "Jose",
    apellido: "Fuentes",
    cedula: "1234567899",
    telefono: "095000111",
    departamento: "MONTEVIDEO",
    necesita_asistencia_movilidad: false,
  },
  {
    nombre: "",
    apellido: "Amendola",
    cedula: "12345678",
    telefono: "095000111",
    departamento: "MONTEVIDEO",
    necesita_asistencia_movilidad: false,
  },
  {
    nombre: "Josefina",
    apellido: "",
    cedula: "12345678",
    telefono: "095000111",
    departamento: "MONTEVIDEO",
    necesita_asistencia_movilidad: false,
  },
  {
    nombre: "Luciana",
    apellido: "Perez",
    cedula: "",
    telefono: "095000111",
    departamento: "MONTEVIDEO",
    necesita_asistencia_movilidad: false,
  },
  {
    nombre: "Ariel",
    apellido: "Topo",
    cedula: "12345678",
    telefono: "",
    departamento: "MONTEVIDEO",
    necesita_asistencia_movilidad: false,
  },
  {
    nombre: "Mathias",
    apellido: "Castro",
    cedula: "12345678",
    telefono: "095000111",
    departamento: "",
    necesita_asistencia_movilidad: false,
  },
  {
    nombre: "Pedro",
    apellido: "Picapiedra",
    cedula: "12345678",
    telefono: "095000111",
    departamento: "Paraje",
    necesita_asistencia_movilidad: false,
  },
  {
    nombre: "Raul",
    apellido: "Gonzalez",
    cedula: "12345678",
    telefono: "095000111",
    departamento: "MONTEVIDEO",
    necesita_asistencia_movilidad: true,
  },
  {
    nombre: "No@mbre",
    apellido: "Jorge",
    cedula: "12345678",
    telefono: "095000111",
    departamento: "MONTEVIDEO",
    necesita_asistencia_movilidad: false,
  },
  {
    nombre: "Nicolas",
    apellido: "Ape$llido",
    cedula: "12345678",
    telefono: "095000111",
    departamento: "MONTEVIDEO",
    necesita_asistencia_movilidad: false,
  },
  {
    nombre: "Nadia",
    apellido: "Apell7ido",
    cedula: "12345678",
    telefono: "095000111",
    departamento: "MONTEVIDEO",
    necesita_asistencia_movilidad: false,
  },
  {
    nombre: "Joselo",
    apellido: "Pelaez",
    cedula: "12345678",
    telefono: "095000111",
    departamento: "MONTEVIDEO",
    necesita_asistencia_movilidad: false,
  },
];
